authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
]

geekshop/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
import mainapp.views as mainapp
import authapp.views as authapp

urlpatterns = [
    url(r'^$', mainapp.index, name='main'),
    url(r'^products/', include('mainapp.urls', namespace='products')),
    url(r'^contact/', mainapp.contact, name='contact'),
    # url(r'^index', mainapp.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.conf.urls import url
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
   url('^$', mainapp.products, name='index'),
   # url(r'^category/(?P<pk>\d+)/$', mainapp.products, name='product'),
   path('category/<int:pk>/', mainapp.products, name='category'),
]

mainapp/models.py
from django.db import models

# Create your models here.


class ProductCategory(models.Model):
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    name = models.CharField(verbose_name='Имя категории', max_length=128, unique=True)
    description = models.TextField(verbose_name='Описание категории', blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import ProductCategory, Product
from basketapp.models import Basket


def index(request):
    return render(request, 'mainapp/index.html')


def products(request, pk=None):
    print(pk)

    title = 'продукты'
    links_menu = ProductCategory.objects.all()
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    if pk is not None:
        if pk == 0:
            product_list = Product.objects.all().order_by('price')
            category = {'name': 'все'}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            product_list = Product.objects.filter(category__pk=pk).order_by('price')

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': product_list,
            'basket': basket,
        }

        return render(request, 'mainapp/product_list.html', content)

    same_products = Product.objects.all()[3:5]

    content = {
        'title': title,
        'links_menu': links_menu,
        'same_products': same_products,
    }

    return render(request, 'mainapp/products.html', content)


# def products(request, pk=None):
#     if pk:
#         category = get_object_or_404(ProductCategory, pk=pk)
#         product_list = Product.objects.filter(category=category.id)
#     else:
#         product_list = Product.objects.all()
#
#     context = {'products': product_list}
#
#     product = ProductCategory.objects.all()
#     prod = {'product': product}
#     return render(request, 'mainapp/products.html', prod)


def contact(request):
    return render(request, 'mainapp/contact.html')

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>
<body>
	<div class="container">

        {% block content %}
            {% block menu %}
            {% endblock %}
        {% endblock %}

	</div>

    {% block footer %}
        <div class="footer">
            <div class="clearfix">
                <div class="text-footer">
                    <h3>контакты</h3>
                </div>
                <div class="text-footer">
                    <h3>полезная информация</h3>
                </div>
                <div class="text-footer clearfix">
                    <h3>Оставайтесь на связи</h3>
                    <p>Подписаться на новости и рассылки</p>
                    <form>
                        <input type="email" name="email" placeholder="ваш email">
                        <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                    </form>
                </div>
            </div>
            <p class="small">&copy; GB 2017</p>
            <div class="social">
                <a href="#" class="social1"></a>
                <a href="#" class="social2"></a>
                <a href="#" class="social3"></a>
                <a href="#" class="social4"></a>
            </div>
            <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
        </div>
    {% endblock %}

</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
    Контакты
{% endblock %}

{% block content %}
    <div class="hero">
        {% block menu %}
            {% include 'mainapp/includes/inc_menu.html' %}
        {% endblock %}
        <h1>наши контакты</h1>
    </div>

		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>
    <div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
	Магазин
{% endblock %}

{% block content %}
	<div class="slider">
		{% block menu %}
            {% include 'mainapp/includes/inc_menu.html' %}
        {% endblock %}
		<div class="text-slider">
				<h3 class="green">тенденции</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
		</div>
		<div class="navi">
			<a href="#"></a><a href="#"></a><a href="#"></a>
		</div>
	</div>
	<div class="featured">
		<div class="featured-menu">
			<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
		</div>
		<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
		<div class="clearfix"></div>
		<div class="tab-content">
			<div class="block">
				<a href="#"><img src="{% static 'img/product-1.jpg' %}" alt="">
					<div class="text">
						<img src="{% static 'img/icon-hover.png' %}" alt="img">
						<h4>Отличный стул</h4>
						<p>Расположитесь комфортно. </p>
					</div></a>
			</div>
			<div class="block">
				<a href="#"><img src="{% static 'img/product-2.jpg' %}" alt="">
					<div class="text">
						<img src="{% static 'img/icon-hover.png' %}" alt="">
						<h4>Стул повышенного качества</h4>
						<p>Не оторваться. </p>
					</div>
				</a>
			</div>
		</div>
	</div>
	<div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/product_list.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}



{% block content %}
    <div class="hero-white">
        {% block menu %}
            {% include 'mainapp/includes/inc_menu.html' %}
        {% endblock %}
    </div>

  <div class="details">
    <div class="links clearfix">
      {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="products_list">
      <div class="title clearfix">
        <h2>
          Категория: "{{ category.name|title }}"
        </h2>
      </div>
      <div class="category-products clearfix">
          {% for product in products %}
          <div class="block">
            <a href="{% url 'basket:add' product.pk %}">
              <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
              <div class="text">
                  <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                  <h4>{{ product.name }}</h4>
                  {% for item in basket %}
                      {% if item.product == product %}
                          <div>{{ item.quantity }}</div>
                      {% endif %}
                  {% endfor %}
                  <p>{{ product.description }}</p>
                  <a href="{% url 'basket:add' product.pk %}">Добавить в корзину</a>
                    <br>
                  <a href="{% url 'basket:remove' product.pk %}">Удалить из корзины</a>
              </div>
            </a>
          </div>
        {% endfor %}

      </div>
    </div>
  </div>

  <div class="clr"></div>

{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
    Каталог
{% endblock %}

{% block content %}
    <div class="hero-white">
		{% block menu %}
            {% include 'mainapp/includes/inc_menu.html' %}
        {% endblock %}
	</div>
		<div class="details">
			<div class="links clearfix">
				{% include 'mainapp/includes/inc_categories_menu.html' %}
			</div>
			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="{% static 'img/slider1.jpg' %}">
					</div>
					<div class="slider-control">
						<div class="block">
							<a href="#"><img src="{% static 'img/controll.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static 'img/controll1.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static 'img/controll2.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">Отличный стул</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price"> 2585.9 <span>руб</span></p>
					<a href="#" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						<p>Расположитесь комфортно.</p>
						<p>Отличное качество материалов
						позволит вам это.</p>
						<p>Различные цвета</p>
						<p>высочайший уровень
						эргономики и прочность.</p>
					</div>
				</div>
			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
				</div>
				<div class="related-products clearfix">
					<div class="block">
						<a href="#"><img src="{% static 'img/product-11.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'img/product-21.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'img/product-31.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>

				</div>
			</div>
		</div>

		<div class="clr"></div>
{% endblock %}